---
include:
  - board: nice_nano_v2
    shield: eyelash_sofle_central_dongle nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_central_dongle
  - board: nice_nano_v2
    shield: eyelash_sofle_left nice_view_custom
  - board: nice_nano_v2
    shield: eyelash_sofle_right nice_view_custom
  - board: nice_nano_v2
    shield: settings_reset
