---
include:
  - board: nice_nano_v2
    shield: eyeslash_sofle_central_dongle dongle_display
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyeslash_sofle_central_dongle
  - board: nice_nano_v2
    shield: eyeslash_sofle_central_dongle dongle_display
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyeslash_sofle_central_dongle_oled
  - board: nice_nano_v2
    shield: eyeslash_sofle_peripheral_left nice_view_custom
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: eyeslash_sofle_peripheral_right nice_view_custom
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset
